name: Build and Publish

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

env:
  NUGET_SOURCE: https://nuget.pkg.github.com/AndrewMcLachlan/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: |
          8.x
          9.x
          10.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Get version info
      id: get-version-number
      uses: AndrewMcLachlan/Actions/get-version-number-from-project@v4
      with:
        project: Directory.Build.props

    - name: Set package version
      id: set-version
      run: echo "package-version=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.${{ steps.get-version-number.outputs.patch }}-ci.${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Restore
      run: dotnet restore Postie.slnx

    - name: Build
      run: dotnet build Postie.slnx --no-restore --configuration Release --p:Version=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.${{ steps.get-version-number.outputs.patch }}.0 --p:FileVersion=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.${{ steps.get-version-number.outputs.patch }}.${{ github.run_number }} --p:InformationalVersion=${{ steps.set-version.outputs.package-version }}

    - name: Test
      run: dotnet test Postie.slnx --no-build --configuration Release --verbosity normal

    - name: Package
      run: dotnet pack Postie.slnx --no-restore --no-build -o ${{ github.workspace }}/publish --configuration Release --p:Version=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.${{ steps.get-version-number.outputs.patch }}.0 --p:PackageVersion=${{ steps.set-version.outputs.package-version }}

    - name: Publish Packages
      if: ((github.event_name == 'workflow_dispatch' || github.event_name == 'push') && github.ref == 'refs/heads/main')
      run: dotnet nuget push ${{ github.workspace }}/publish/**/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.NUGET_SOURCE }} --skip-duplicate
